# Generated by Django 4.2.4 on 2023-09-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_last_update_alter_ticket_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
