# Generated by Django 4.2.4 on 2023-09-21 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_alter_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIntervention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('intervention_debut', models.DateTimeField(verbose_name='intervention debut')),
                ('intervention_end', models.DateTimeField(verbose_name='intervention end')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_id', to='tickets.ticket')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
